word = input()
#print(word)
word = word.replace("c=", "c")
word = word.replace("c-", "c")
word = word.replace("dz=", "c")
word = word.replace("d-", "c")
word = word.replace("lj", "c")
word = word.replace("nj", "c")
word = word.replace("s=", "c")
word = word.replace("z=", "c")
#print(word)
print(len(word))